(() => {
  'use strict';

  const templates = {
    horizontalPress: {
      description: 'Spinta orizzontale per petto, tricipiti e deltoide anteriore. Mantieni il movimento controllato e una traiettoria ripetibile.',
      setup: ['Stabilizza piedi e bacino.', 'Mantieni scapole addotte e depresse senza perdere il contatto con l’appoggio.'],
      execution: ['Scendi con controllo fino a una profondità tollerata.', 'Spingi senza far rimbalzare il carico e senza perdere l’assetto delle spalle.'],
      errors: ['Gomiti eccessivamente aperti.', 'Spalle che avanzano nella parte bassa.', 'Rimbalzo o traiettoria diversa a ogni ripetizione.'],
      tips: ['Usa un carico che permetta di mantenere tecnica e range di movimento.', 'Interrompi la serie se compare dolore articolare non abituale.'],
    },
    fly: {
      description: 'Adduzione dell’omero con enfasi sul petto. Il gomito resta leggermente flesso e l’escursione deve rimanere confortevole.',
      setup: ['Stabilizza torace e scapole.', 'Mantieni una leggera flessione del gomito per tutta la serie.'],
      execution: ['Apri lentamente finché senti allungamento senza dolore.', 'Richiudi guidando il movimento con il petto, senza trasformarlo in una spinta.'],
      errors: ['Carico eccessivo e braccia che diventano rigide.', 'Perdita del controllo nella fase di apertura.', 'Spalle sollevate verso le orecchie.'],
      tips: ['Privilegia tensione continua e controllo.', 'Riduci l’escursione se senti stress nella parte anteriore della spalla.'],
    },
    verticalPress: {
      description: 'Spinta verticale per deltoidi e tricipiti. Richiede controllo del tronco e una traiettoria compatibile con la mobilità della spalla.',
      setup: ['Contrai addome e glutei.', 'Posiziona polsi e gomiti sotto il carico.'],
      execution: ['Spingi verso l’alto senza inarcare eccessivamente la zona lombare.', 'Ritorna con controllo mantenendo il carico sopra una base stabile.'],
      errors: ['Iperestensione lombare marcata.', 'Polsi piegati all’indietro.', 'Escursione forzata oltre la mobilità disponibile.'],
      tips: ['Una presa leggermente più stretta può risultare più confortevole.', 'Scegli una variante guidata se fai fatica a stabilizzare il tronco.'],
    },
    verticalPull: {
      description: 'Tirata verticale per gran dorsale e flessori del gomito. Inizia il gesto controllando le scapole e porta i gomiti verso il basso.',
      setup: ['Stabilizza il bacino e il torace.', 'Usa una presa che non provochi fastidio a polsi o spalle.'],
      execution: ['Porta i gomiti verso i fianchi mantenendo il petto alto.', 'Risalita controllata fino a un allungamento gestibile.'],
      errors: ['Oscillare con il busto.', 'Tirare dietro la nuca.', 'Accorciare eccessivamente la fase di allungamento.'],
      tips: ['Pensa ai gomiti, non alle mani.', 'Riduci il carico se devi usare slancio.'],
    },
    horizontalPull: {
      description: 'Tirata orizzontale per dorsali, romboidi e trapezio. Mantieni il busto stabile e guida il movimento con gomiti e scapole.',
      setup: ['Crea un appoggio stabile per piedi e tronco.', 'Allunga le braccia senza perdere il controllo delle spalle.'],
      execution: ['Tira i gomiti indietro senza sollevare le spalle.', 'Ritorna lentamente mantenendo tensione.'],
      errors: ['Eccessivo slancio del busto.', 'Spalle che salgono verso le orecchie.', 'Accorciare la fase eccentrica.'],
      tips: ['Scegli il punto di arrivo in base alla variante e alla presa.', 'Usa supporto al petto se vuoi ridurre il coinvolgimento lombare.'],
    },
    rearDelt: {
      description: 'Movimento per deltoidi posteriori e stabilizzatori scapolari. Carico moderato, controllo elevato e spalle lontane dalle orecchie.',
      setup: ['Mantieni torace stabile.', 'Parti con gomiti leggermente flessi.'],
      execution: ['Apri le braccia guidando con i gomiti.', 'Fermati prima di perdere il controllo della scapola.'],
      errors: ['Usare slancio.', 'Coinvolgere troppo il trapezio superiore.', 'Trasformare il gesto in un rematore pesante.'],
      tips: ['Pausa breve nella posizione di massima contrazione.', 'Usa ripetizioni pulite e regolari.'],
    },
    curl: {
      description: 'Flessione del gomito per bicipite, brachiale e brachioradiale. Il gomito resta stabile e il carico viene controllato in entrambe le fasi.',
      setup: ['Mantieni polsi neutri o nella posizione prevista dalla variante.', 'Stabilizza spalle e tronco.'],
      execution: ['Fletti il gomito senza spostarlo in avanti in modo eccessivo.', 'Scendi lentamente fino all’estensione controllata.'],
      errors: ['Slancio del busto.', 'Polsi che cedono.', 'Perdere tensione nella parte bassa.'],
      tips: ['Riduci il carico se il gomito si sposta molto.', 'Mantieni la stessa velocità da una ripetizione all’altra.'],
    },
    triceps: {
      description: 'Estensione del gomito per il tricipite. Mantieni la spalla stabile e completa il movimento senza compensare con il tronco.',
      setup: ['Posiziona gomiti stabili e polsi neutri.', 'Crea una base stabile con piedi e addome.'],
      execution: ['Estendi il gomito fino a una chiusura controllata.', 'Ritorna lentamente senza perdere la posizione del braccio.'],
      errors: ['Gomiti che si aprono senza controllo.', 'Movimento del busto per spostare il carico.', 'Carico troppo alto e range ridotto.'],
      tips: ['Scegli corda, barra o maniglia in base al comfort.', 'Nelle varianti sopra la testa usa un carico che non irriti il gomito.'],
    },
    squat: {
      description: 'Schema di accosciata per quadricipiti, glutei e tronco. Profondità, stance e traiettoria dipendono dalla mobilità e dalla struttura individuale.',
      setup: ['Distribuisci il peso su tutto il piede.', 'Crea pressione addominale prima di scendere.'],
      execution: ['Scendi mantenendo ginocchia in linea con i piedi.', 'Risalita spingendo il pavimento senza perdere l’assetto del tronco.'],
      errors: ['Talloni che si sollevano senza controllo.', 'Ginocchia che collassano verso l’interno.', 'Perdita marcata della posizione lombare.'],
      tips: ['Usa una profondità che consenta controllo.', 'Regola stance e rialzo del tallone in base alla tua mobilità.'],
    },
    legPress: {
      description: 'Spinta guidata per quadricipiti e glutei. La posizione dei piedi modifica l’enfasi, ma il bacino deve restare stabile sullo schienale.',
      setup: ['Posiziona i piedi in modo simmetrico.', 'Mantieni bacino e schiena aderenti all’appoggio.'],
      execution: ['Scendi finché il bacino resta stabile.', 'Spingi senza bloccare violentemente le ginocchia.'],
      errors: ['Bacino che si stacca e si arrotola.', 'Ginocchia che collassano all’interno.', 'Escursione troppo corta per usare più carico.'],
      tips: ['Regola sedile e pedana prima di caricare.', 'Nella variante monopodalica riduci il carico e controlla il bacino.'],
    },
    unilateralLeg: {
      description: 'Movimento monopodalico per quadricipiti, glutei e stabilità. La priorità è mantenere equilibrio e traiettoria coerente.',
      setup: ['Trova una distanza dei piedi stabile.', 'Mantieni il piede anteriore completamente appoggiato.'],
      execution: ['Scendi controllando ginocchio e bacino.', 'Risalita spingendo attraverso il piede della gamba di lavoro.'],
      errors: ['Passo troppo corto o troppo lungo per la mobilità disponibile.', 'Perdita di equilibrio e rimbalzo.', 'Ginocchio che collassa verso l’interno.'],
      tips: ['Usa un supporto leggero se l’equilibrio limita il muscolo.', 'Conta separatamente le ripetizioni per lato.'],
    },
    hinge: {
      description: 'Estensione d’anca per femorali, glutei ed erettori spinali. Il movimento nasce dall’anca con colonna e carico controllati.',
      setup: ['Mantieni il carico vicino al corpo.', 'Crea pressione addominale e una posizione neutra confortevole.'],
      execution: ['Porta indietro il bacino mantenendo una lieve flessione delle ginocchia.', 'Risalita estendendo l’anca senza iperestendere la schiena.'],
      errors: ['Carico lontano dal corpo.', 'Perdita marcata della posizione lombare.', 'Trasformare il movimento in uno squat.'],
      tips: ['Fermati quando l’anca non arretra più senza compensi.', 'Aumenta il carico solo mantenendo la stessa tecnica.'],
    },
    kneeExtension: {
      description: 'Estensione del ginocchio con enfasi sul quadricipite. Regola la macchina per allineare il ginocchio al perno.',
      setup: ['Allinea il ginocchio al fulcro della macchina.', 'Stabilizza bacino e schiena sul sedile.'],
      execution: ['Estendi con controllo senza dare slancio.', 'Ritorna lentamente mantenendo tensione.'],
      errors: ['Perno disallineato.', 'Colpo nella chiusura del ginocchio.', 'Sollevare il bacino dal sedile.'],
      tips: ['Usa un’escursione confortevole.', 'Una pausa breve in alto aumenta il controllo.'],
    },
    kneeFlexion: {
      description: 'Flessione del ginocchio per i femorali. Mantieni il bacino stabile e controlla la fase di ritorno.',
      setup: ['Allinea il ginocchio al perno.', 'Posiziona il rullo sopra la parte bassa della gamba senza comprimere il tendine.'],
      execution: ['Fletti il ginocchio senza sollevare il bacino.', 'Ritorna lentamente fino a un allungamento controllato.'],
      errors: ['Bacino che si solleva.', 'Movimento esplosivo e incontrollato.', 'Range ridotto per carico eccessivo.'],
      tips: ['Mantieni le anche stabili.', 'Alterna varianti sedute e sdraiate se disponibili.'],
    },
    calf: {
      description: 'Flessione plantare per gastrocnemio e soleo. Usa un’escursione controllata e una pausa nelle posizioni estreme.',
      setup: ['Appoggia l’avampiede in modo stabile.', 'Mantieni caviglia e ginocchio allineati.'],
      execution: ['Scendi lentamente verso l’allungamento.', 'Sali fino alla massima contrazione senza rimbalzare.'],
      errors: ['Rimbalzo rapido.', 'Escursione ridotta.', 'Caviglie che cedono verso l’interno o l’esterno.'],
      tips: ['Pausa un istante in basso e in alto.', 'Ginocchio teso enfatizza maggiormente il gastrocnemio; flesso il soleo.'],
    },
    core: {
      description: 'Esercizio per il controllo del tronco. Mantieni respirazione, bacino e colonna nella posizione prevista dalla variante.',
      setup: ['Crea tensione addominale senza trattenere eccessivamente il respiro.', 'Posiziona bacino e gabbia toracica in modo controllato.'],
      execution: ['Muoviti lentamente mantenendo il tronco stabile.', 'Interrompi la serie quando perdi la posizione.'],
      errors: ['Compensare con la zona lombare.', 'Movimento troppo veloce.', 'Trattenere il respiro per tutta la serie.'],
      tips: ['Qualità prima della durata.', 'Scegli una variante che puoi controllare senza dolore.'],
    },
  };

  const raw = [
    { id:'barbell-bench-press', name:'Panca piana con bilanciere', aliases:['Panca piana','Bench press','Barbell bench press','Panca bilanciere'], muscle:'Petto', primary:['Grande pettorale'], secondary:['Tricipiti','Deltoide anteriore'], equipment:['Bilanciere','Panca'], difficulty:'Intermedio', pattern:'horizontalPress', alternatives:['Spinte manubri su panca piana','Chest press piana'] },
    { id:'dumbbell-bench-press', name:'Spinte manubri su panca piana', aliases:['Panca piana manubri','Dumbbell bench press','Spinte manubri panca piana'], muscle:'Petto', primary:['Grande pettorale'], secondary:['Tricipiti','Deltoide anteriore'], equipment:['Manubri','Panca'], difficulty:'Intermedio', pattern:'horizontalPress', alternatives:['Panca piana con bilanciere','Chest press piana'] },
    { id:'incline-barbell-bench', name:'Panca inclinata con bilanciere', aliases:['Incline bench press','Panca inclinata bilanciere'], muscle:'Petto alto', primary:['Fasci clavicolari del pettorale'], secondary:['Deltoide anteriore','Tricipiti'], equipment:['Bilanciere','Panca inclinata'], difficulty:'Intermedio', pattern:'horizontalPress', alternatives:['Panca inclinata Multipower','Chest press inclinata'] },
    { id:'incline-dumbbell-press', name:'Spinte manubri su panca inclinata', aliases:['Panca inclinata manubri','Incline dumbbell press'], muscle:'Petto alto', primary:['Fasci clavicolari del pettorale'], secondary:['Deltoide anteriore','Tricipiti'], equipment:['Manubri','Panca inclinata'], difficulty:'Intermedio', pattern:'horizontalPress', alternatives:['Panca inclinata con bilanciere','Chest press inclinata'] },
    { id:'incline-smith-press', name:'Panca inclinata Multipower', aliases:['Panca inclinata Smith Machine','Incline Smith press','Panca inclinata multipower'], muscle:'Petto alto', primary:['Fasci clavicolari del pettorale'], secondary:['Deltoide anteriore','Tricipiti'], equipment:['Multipower','Panca inclinata'], difficulty:'Base', pattern:'horizontalPress', alternatives:['Chest press inclinata','Spinte manubri su panca inclinata'] },
    { id:'chest-press-flat', name:'Chest press piana', aliases:['Chest press','Machine chest press','Pressa petto'], muscle:'Petto', primary:['Grande pettorale'], secondary:['Tricipiti','Deltoide anteriore'], equipment:['Macchina chest press'], difficulty:'Base', pattern:'horizontalPress', alternatives:['Panca piana con bilanciere','Spinte manubri su panca piana'] },
    { id:'incline-chest-press', name:'Chest press inclinata', aliases:['Incline chest press','Chest press alta'], muscle:'Petto alto', primary:['Fasci clavicolari del pettorale'], secondary:['Tricipiti','Deltoide anteriore'], equipment:['Macchina chest press'], difficulty:'Base', pattern:'horizontalPress', alternatives:['Panca inclinata Multipower','Spinte manubri su panca inclinata'] },
    { id:'flat-dumbbell-fly', name:'Croci manubri su panca piana', aliases:['Croci manubri panca piana','Dumbbell fly','Croci con manubri'], muscle:'Petto', primary:['Grande pettorale'], secondary:['Deltoide anteriore'], equipment:['Manubri','Panca'], difficulty:'Intermedio', pattern:'fly', alternatives:['Croci ai cavi','Peck Deck'] },
    { id:'cable-fly', name:'Croci ai cavi', aliases:['Cable fly','Crossover ai cavi','Croci cavi'], muscle:'Petto', primary:['Grande pettorale'], secondary:['Deltoide anteriore'], equipment:['Cavi'], difficulty:'Base', pattern:'fly', alternatives:['Peck Deck','Croci manubri su panca piana'] },
    { id:'pec-deck', name:'Peck Deck', aliases:['Pec deck','Butterfly machine','Macchina croci'], muscle:'Petto', primary:['Grande pettorale'], secondary:['Deltoide anteriore'], equipment:['Peck deck'], difficulty:'Base', pattern:'fly', alternatives:['Croci ai cavi','Croci manubri su panca piana'] },
    { id:'chest-dip', name:'Dips per il petto', aliases:['Dips','Dip petto','Chest dips','Parallele petto'], muscle:'Petto', primary:['Grande pettorale'], secondary:['Tricipiti','Deltoide anteriore'], equipment:['Parallele'], difficulty:'Avanzato', pattern:'horizontalPress', alternatives:['Chest press piana','Push-up'] },
    { id:'push-up', name:'Push-up', aliases:['Piegamenti','Piegamenti sulle braccia','Flessioni'], muscle:'Petto', primary:['Grande pettorale'], secondary:['Tricipiti','Deltoide anteriore','Core'], equipment:['Corpo libero'], difficulty:'Base', pattern:'horizontalPress', alternatives:['Panca piana con bilanciere','Chest press piana'] },

    { id:'lat-pulldown', name:'Lat Machine', aliases:['Lat machine avanti','Lat pulldown','Pulldown verticale','Lat machine presa larga'], muscle:'Dorso', primary:['Gran dorsale'], secondary:['Bicipiti','Grande rotondo'], equipment:['Lat machine'], difficulty:'Base', pattern:'verticalPull', alternatives:['Trazioni alla sbarra','Pulldown presa neutra'] },
    { id:'pull-up', name:'Trazioni alla sbarra', aliases:['Trazioni','Pull-up','Chin-up presa prona'], muscle:'Dorso', primary:['Gran dorsale'], secondary:['Bicipiti','Grande rotondo','Core'], equipment:['Sbarra'], difficulty:'Avanzato', pattern:'verticalPull', alternatives:['Lat Machine','Trazioni assistite'] },
    { id:'neutral-pulldown', name:'Pulldown presa neutra', aliases:['Lat machine presa neutra','Neutral grip pulldown'], muscle:'Dorso', primary:['Gran dorsale'], secondary:['Bicipiti','Grande rotondo'], equipment:['Cavi','Maniglia neutra'], difficulty:'Base', pattern:'verticalPull', alternatives:['Lat Machine','Trazioni alla sbarra'] },
    { id:'rope-pulldown', name:'Pulldown con fune', aliases:['Pulldown fune','Rope pulldown','Lat pulldown con corda'], muscle:'Dorso', primary:['Gran dorsale'], secondary:['Grande rotondo','Bicipiti'], equipment:['Cavi','Corda'], difficulty:'Intermedio', pattern:'verticalPull', alternatives:['Pullover ai cavi','Lat Machine'] },
    { id:'barbell-row', name:'Rematore con bilanciere', aliases:['Rematore','Barbell row','Bent over row','Rematore bilanciere'], muscle:'Dorso', primary:['Gran dorsale','Romboidi'], secondary:['Trapezio','Bicipiti','Erettori spinali'], equipment:['Bilanciere'], difficulty:'Intermedio', pattern:'horizontalPull', alternatives:['T-Bar Row petto supportato','Pulley basso'] },
    { id:'one-arm-dumbbell-row', name:'Rematore con manubrio', aliases:['Rematore manubrio','One arm dumbbell row'], muscle:'Dorso', primary:['Gran dorsale','Romboidi'], secondary:['Bicipiti','Trapezio'], equipment:['Manubrio','Panca'], difficulty:'Base', pattern:'horizontalPull', alternatives:['Pulley monolaterale','Rematore con bilanciere'] },
    { id:'chest-supported-tbar-row', name:'T-Bar Row petto supportato', aliases:['T bar row petto supportato','Chest supported T-bar row','T-Bar Row supportato'], muscle:'Dorso', primary:['Gran dorsale','Romboidi'], secondary:['Trapezio','Bicipiti'], equipment:['T-Bar supportata'], difficulty:'Base', pattern:'horizontalPull', alternatives:['Rematore macchina','Pulley basso'] },
    { id:'seated-cable-row', name:'Pulley basso', aliases:['Pulley','Seated cable row','Rematore al cavo basso'], muscle:'Dorso', primary:['Gran dorsale','Romboidi'], secondary:['Trapezio','Bicipiti'], equipment:['Cavi'], difficulty:'Base', pattern:'horizontalPull', alternatives:['Pulley monolaterale','Rematore macchina'] },
    { id:'single-arm-cable-row', name:'Pulley monolaterale', aliases:['Pulley unilaterale','Single arm cable row','Rematore cavo monolaterale'], muscle:'Dorso', primary:['Gran dorsale'], secondary:['Romboidi','Bicipiti'], equipment:['Cavi','Maniglia singola'], difficulty:'Base', pattern:'horizontalPull', alternatives:['Rematore con manubrio','Pulley basso'] },
    { id:'seated-row-machine', name:'Rematore macchina', aliases:['Seated row machine','Machine row','Row machine'], muscle:'Dorso', primary:['Gran dorsale','Romboidi'], secondary:['Trapezio','Bicipiti'], equipment:['Macchina rematore'], difficulty:'Base', pattern:'horizontalPull', alternatives:['Pulley basso','T-Bar Row petto supportato'] },
    { id:'high-row-machine', name:'High Row Machine', aliases:['High row','Hammer high row','Rematore alto macchina'], muscle:'Dorso', primary:['Gran dorsale','Grande rotondo'], secondary:['Romboidi','Bicipiti'], equipment:['Macchina high row'], difficulty:'Base', pattern:'horizontalPull', alternatives:['Lat Machine','Rematore macchina'] },
    { id:'straight-arm-pulldown', name:'Pullover ai cavi', aliases:['Straight arm pulldown','Pulldown braccia tese','Pullover cavo'], muscle:'Dorso', primary:['Gran dorsale'], secondary:['Grande rotondo','Tricipite capo lungo'], equipment:['Cavi'], difficulty:'Base', pattern:'verticalPull', alternatives:['Pulldown con fune','Pullover manubrio'] },
    { id:'deadlift', name:'Stacco da terra', aliases:['Deadlift','Stacco convenzionale'], muscle:'Catena posteriore', primary:['Glutei','Femorali','Erettori spinali'], secondary:['Gran dorsale','Trapezio','Avambracci'], equipment:['Bilanciere'], difficulty:'Avanzato', pattern:'hinge', alternatives:['Stacchi Rumeni','Trap bar deadlift'] },
    { id:'back-extension', name:'Hyperextension', aliases:['Iperestensioni','Back extension','Hyper extension'], muscle:'Catena posteriore', primary:['Glutei','Erettori spinali'], secondary:['Femorali'], equipment:['Panca romana'], difficulty:'Base', pattern:'hinge', alternatives:['Stacchi Rumeni','Glute bridge'] },

    { id:'barbell-overhead-press', name:'Military Press con bilanciere', aliases:['Military press','Overhead press','OHP','Lento avanti'], muscle:'Spalle', primary:['Deltoide anteriore','Deltoide laterale'], secondary:['Tricipiti','Trapezio superiore'], equipment:['Bilanciere'], difficulty:'Intermedio', pattern:'verticalPress', alternatives:['Military Press Smith Machine','Shoulder press con manubri'] },
    { id:'smith-overhead-press', name:'Military Press Smith Machine', aliases:['Military press multipower','Smith machine shoulder press','Military Press Smith'], muscle:'Spalle', primary:['Deltoide anteriore','Deltoide laterale'], secondary:['Tricipiti'], equipment:['Multipower','Panca'], difficulty:'Base', pattern:'verticalPress', alternatives:['Shoulder press macchina','Military Press con bilanciere'] },
    { id:'dumbbell-shoulder-press', name:'Shoulder press con manubri', aliases:['Spinte manubri spalle','Dumbbell shoulder press','Lento manubri'], muscle:'Spalle', primary:['Deltoide anteriore','Deltoide laterale'], secondary:['Tricipiti'], equipment:['Manubri','Panca'], difficulty:'Intermedio', pattern:'verticalPress', alternatives:['Shoulder press macchina','Military Press con bilanciere'] },
    { id:'machine-shoulder-press', name:'Shoulder press macchina', aliases:['Machine shoulder press','Press spalle macchina'], muscle:'Spalle', primary:['Deltoide anteriore','Deltoide laterale'], secondary:['Tricipiti'], equipment:['Macchina shoulder press'], difficulty:'Base', pattern:'verticalPress', alternatives:['Shoulder press con manubri','Military Press Smith Machine'] },
    { id:'lateral-raise', name:'Alzate laterali', aliases:['Alzate laterali manubri','Lateral raise'], muscle:'Spalle', primary:['Deltoide laterale'], secondary:['Trapezio superiore'], equipment:['Manubri'], difficulty:'Base', pattern:'rearDelt', alternatives:['Alzate laterali da seduto','Alzate laterali ai cavi'] },
    { id:'seated-lateral-raise', name:'Alzate laterali da seduto', aliases:['Seated lateral raise','Alzate laterali seduto'], muscle:'Spalle', primary:['Deltoide laterale'], secondary:['Trapezio superiore'], equipment:['Manubri','Panca'], difficulty:'Base', pattern:'rearDelt', alternatives:['Alzate laterali','Alzate laterali ai cavi'] },
    { id:'cable-lateral-raise', name:'Alzate laterali ai cavi', aliases:['Cable lateral raise','Alzate laterali cavo'], muscle:'Spalle', primary:['Deltoide laterale'], secondary:['Trapezio superiore'], equipment:['Cavi'], difficulty:'Base', pattern:'rearDelt', alternatives:['Alzate laterali','Alzate laterali da seduto'] },
    { id:'reverse-pec-deck', name:'Peck Back', aliases:['Reverse pec deck','Reverse fly machine','Peck deck inversa','Deltoidi posteriori macchina'], muscle:'Deltoidi posteriori', primary:['Deltoide posteriore'], secondary:['Romboidi','Trapezio medio'], equipment:['Peck deck inversa'], difficulty:'Base', pattern:'rearDelt', alternatives:['Face Pull','Croci inverse ai cavi'] },
    { id:'face-pull', name:'Face Pull', aliases:['Face pull cavi','Tirate al viso'], muscle:'Deltoidi posteriori', primary:['Deltoide posteriore','Romboidi'], secondary:['Cuffia dei rotatori','Trapezio medio'], equipment:['Cavi','Corda'], difficulty:'Base', pattern:'rearDelt', alternatives:['Peck Back','Croci inverse ai cavi'] },
    { id:'upright-row', name:'Tirate al mento', aliases:['Upright row','Tirate verticali'], muscle:'Spalle', primary:['Deltoide laterale','Trapezio superiore'], secondary:['Bicipiti'], equipment:['Bilanciere o cavo'], difficulty:'Intermedio', pattern:'verticalPull', alternatives:['Alzate laterali','High pull leggero'] },

    { id:'barbell-curl', name:'Curl con bilanciere', aliases:['Barbell curl','Curl bilanciere'], muscle:'Bicipiti', primary:['Bicipite brachiale'], secondary:['Brachiale','Brachioradiale'], equipment:['Bilanciere'], difficulty:'Base', pattern:'curl', alternatives:['Curl con manubri','Curl ai cavi'] },
    { id:'dumbbell-curl', name:'Curl con manubri', aliases:['Dumbbell curl','Curl manubri'], muscle:'Bicipiti', primary:['Bicipite brachiale'], secondary:['Brachiale','Brachioradiale'], equipment:['Manubri'], difficulty:'Base', pattern:'curl', alternatives:['Curl con bilanciere','Curl su panca inclinata'] },
    { id:'incline-dumbbell-curl', name:'Curl su panca inclinata', aliases:['Incline dumbbell curl','Curl panca inclinata'], muscle:'Bicipiti', primary:['Bicipite brachiale'], secondary:['Brachiale'], equipment:['Manubri','Panca inclinata'], difficulty:'Intermedio', pattern:'curl', alternatives:['Bayesian Curl','Curl con manubri'] },
    { id:'hammer-curl', name:'Hammer Curl', aliases:['Curl martello','Hammer curl manubri'], muscle:'Bicipiti', primary:['Brachiale','Brachioradiale'], secondary:['Bicipite brachiale'], equipment:['Manubri'], difficulty:'Base', pattern:'curl', alternatives:['Curl con manubri','Hammer curl ai cavi'] },
    { id:'preacher-curl', name:'Preacher Curl', aliases:['Curl Scott','Curl panca Scott','Scott curl'], muscle:'Bicipiti', primary:['Bicipite brachiale'], secondary:['Brachiale'], equipment:['Panca Scott','Bilanciere o manubri'], difficulty:'Base', pattern:'curl', alternatives:['Curl ai cavi','Curl con bilanciere'] },
    { id:'cable-curl', name:'Curl ai cavi', aliases:['Cable curl','Curl cavo basso'], muscle:'Bicipiti', primary:['Bicipite brachiale'], secondary:['Brachiale'], equipment:['Cavi'], difficulty:'Base', pattern:'curl', alternatives:['Curl con bilanciere','Bayesian Curl'] },
    { id:'bayesian-curl', name:'Bayesian Curl', aliases:['Bayesian cable curl','Curl bayesian','Curl ai cavi dietro il corpo'], muscle:'Bicipiti', primary:['Bicipite brachiale'], secondary:['Brachiale'], equipment:['Cavi','Maniglia singola'], difficulty:'Intermedio', pattern:'curl', alternatives:['Curl su panca inclinata','Curl ai cavi'] },
    { id:'concentration-curl', name:'Curl di concentrazione', aliases:['Concentration curl','Curl concentrato'], muscle:'Bicipiti', primary:['Bicipite brachiale'], secondary:['Brachiale'], equipment:['Manubrio'], difficulty:'Base', pattern:'curl', alternatives:['Preacher Curl','Curl con manubri'] },

    { id:'rope-pushdown', name:'Pushdown con corda', aliases:['Pushdown corda','Rope pushdown','Triceps rope pushdown'], muscle:'Tricipiti', primary:['Tricipite brachiale'], secondary:[], equipment:['Cavi','Corda'], difficulty:'Base', pattern:'triceps', alternatives:['Pushdown con barra','Estensioni sopra la testa ai cavi'] },
    { id:'bar-pushdown', name:'Pushdown con barra', aliases:['Pushdown sbarra','Triceps pushdown','Cable pushdown'], muscle:'Tricipiti', primary:['Tricipite brachiale'], secondary:[], equipment:['Cavi','Barra'], difficulty:'Base', pattern:'triceps', alternatives:['Pushdown con corda','French press'] },
    { id:'overhead-cable-extension', name:'Estensioni dietro la nuca ai cavi', aliases:['Estensioni sopra la testa ai cavi','Overhead cable extension','French press ai cavi'], muscle:'Tricipiti', primary:['Tricipite brachiale - capo lungo'], secondary:['Tricipite laterale e mediale'], equipment:['Cavi','Corda'], difficulty:'Base', pattern:'triceps', alternatives:['French press','Pushdown con corda'] },
    { id:'french-press', name:'French Press', aliases:['French press bilanciere','Estensioni tricipiti sdraiato'], muscle:'Tricipiti', primary:['Tricipite brachiale'], secondary:[], equipment:['Bilanciere EZ','Panca'], difficulty:'Intermedio', pattern:'triceps', alternatives:['Skull Crusher','Estensioni dietro la nuca ai cavi'] },
    { id:'skull-crusher', name:'Skull Crusher', aliases:['Skullcrusher','Estensioni tricipiti EZ'], muscle:'Tricipiti', primary:['Tricipite brachiale'], secondary:[], equipment:['Bilanciere EZ','Panca'], difficulty:'Intermedio', pattern:'triceps', alternatives:['French Press','Pushdown con barra'] },
    { id:'triceps-dip', name:'Dips per tricipiti', aliases:['Dip tricipiti','Bench dip','Parallele tricipiti'], muscle:'Tricipiti', primary:['Tricipite brachiale'], secondary:['Petto','Deltoide anteriore'], equipment:['Parallele o panca'], difficulty:'Intermedio', pattern:'triceps', alternatives:['Panca presa stretta','Pushdown con corda'] },
    { id:'close-grip-bench', name:'Panca presa stretta', aliases:['Close grip bench press','Panca stretta'], muscle:'Tricipiti', primary:['Tricipite brachiale'], secondary:['Petto','Deltoide anteriore'], equipment:['Bilanciere','Panca'], difficulty:'Intermedio', pattern:'horizontalPress', alternatives:['Dips per tricipiti','Pushdown con barra'] },
    { id:'triceps-kickback', name:'Kickback tricipiti', aliases:['Triceps kickback','Kick back'], muscle:'Tricipiti', primary:['Tricipite brachiale'], secondary:[], equipment:['Manubrio o cavo'], difficulty:'Base', pattern:'triceps', alternatives:['Pushdown con corda','Estensioni sopra la testa ai cavi'] },

    { id:'back-squat', name:'Squat con bilanciere', aliases:['Squat','Back squat','Squat bilanciere'], muscle:'Quadricipiti', primary:['Quadricipiti','Glutei'], secondary:['Adduttori','Erettori spinali','Core'], equipment:['Bilanciere','Rack'], difficulty:'Avanzato', pattern:'squat', alternatives:['Hack Squat','Pressa 45 gradi'] },
    { id:'front-squat', name:'Front Squat', aliases:['Squat frontale','Front squat bilanciere'], muscle:'Quadricipiti', primary:['Quadricipiti'], secondary:['Glutei','Core','Dorso alto'], equipment:['Bilanciere','Rack'], difficulty:'Avanzato', pattern:'squat', alternatives:['Hack Squat','Goblet squat'] },
    { id:'hack-squat', name:'Hack Squat', aliases:['Hack squat machine','Pressa hack'], muscle:'Quadricipiti', primary:['Quadricipiti'], secondary:['Glutei','Adduttori'], equipment:['Hack squat'], difficulty:'Base', pattern:'squat', alternatives:['Pressa 45 gradi','Squat con bilanciere'] },
    { id:'leg-press-45', name:'Pressa 45 gradi', aliases:['Leg press 45','Pressa inclinata','Pressa 45°'], muscle:'Quadricipiti', primary:['Quadricipiti'], secondary:['Glutei','Adduttori'], equipment:['Pressa 45°'], difficulty:'Base', pattern:'legPress', alternatives:['Hack Squat','Pressa orizzontale'] },
    { id:'horizontal-leg-press', name:'Pressa orizzontale', aliases:['Horizontal leg press','Pressa seduta'], muscle:'Quadricipiti', primary:['Quadricipiti'], secondary:['Glutei'], equipment:['Pressa orizzontale'], difficulty:'Base', pattern:'legPress', alternatives:['Pressa 45 gradi','Hack Squat'] },
    { id:'single-leg-horizontal-press', name:'Pressa orizzontale gamba singola', aliases:['Pressa singola','Single leg press','Pressa monopodalica'], muscle:'Quadricipiti', primary:['Quadricipiti'], secondary:['Glutei'], equipment:['Pressa orizzontale'], difficulty:'Intermedio', pattern:'legPress', alternatives:['Bulgarian Split Squat','Step-up'] },
    { id:'bulgarian-split-squat', name:'Bulgarian Split Squat', aliases:['Squat bulgaro','Affondo bulgaro','Bulgarian squat'], muscle:'Quadricipiti', primary:['Quadricipiti','Glutei'], secondary:['Adduttori','Core'], equipment:['Panca','Manubri opzionali'], difficulty:'Intermedio', pattern:'unilateralLeg', alternatives:['Affondi camminati','Pressa gamba singola'] },
    { id:'walking-lunge', name:'Affondi camminati', aliases:['Walking lunge','Affondi in camminata'], muscle:'Gambe', primary:['Quadricipiti','Glutei'], secondary:['Adduttori','Core'], equipment:['Corpo libero o manubri'], difficulty:'Intermedio', pattern:'unilateralLeg', alternatives:['Bulgarian Split Squat','Step-up'] },
    { id:'leg-extension', name:'Leg Extension', aliases:['Leg extension machine','Estensioni gambe'], muscle:'Quadricipiti', primary:['Quadricipiti'], secondary:[], equipment:['Leg extension'], difficulty:'Base', pattern:'kneeExtension', alternatives:['Sissy squat assistito','Hack Squat'] },
    { id:'step-up', name:'Step-up', aliases:['Step up panca','Salita su box'], muscle:'Gambe', primary:['Quadricipiti','Glutei'], secondary:['Femorali','Core'], equipment:['Box o panca','Manubri opzionali'], difficulty:'Intermedio', pattern:'unilateralLeg', alternatives:['Affondi camminati','Bulgarian Split Squat'] },
    { id:'hip-thrust', name:'Hip Thrust', aliases:['Hip thrust bilanciere','Spinta d’anca'], muscle:'Glutei', primary:['Grande gluteo'], secondary:['Femorali','Adduttori'], equipment:['Bilanciere','Panca'], difficulty:'Intermedio', pattern:'hinge', alternatives:['Glute Bridge','Romanian Deadlift'] },
    { id:'glute-bridge', name:'Glute Bridge', aliases:['Ponte glutei','Glute bridge a terra'], muscle:'Glutei', primary:['Grande gluteo'], secondary:['Femorali'], equipment:['Corpo libero o bilanciere'], difficulty:'Base', pattern:'hinge', alternatives:['Hip Thrust','Hyperextension'] },
    { id:'hip-abduction', name:'Abductor Machine', aliases:['Abduzioni macchina','Hip abduction machine'], muscle:'Glutei', primary:['Gluteo medio','Gluteo minimo'], secondary:['Tensore fascia lata'], equipment:['Macchina abduttori'], difficulty:'Base', pattern:'unilateralLeg', alternatives:['Abduzioni ai cavi','Camminata laterale con elastico'] },
    { id:'hip-adduction', name:'Adductor Machine', aliases:['Adduttori macchina','Hip adduction machine'], muscle:'Adduttori', primary:['Adduttori'], secondary:['Gracile'], equipment:['Macchina adduttori'], difficulty:'Base', pattern:'unilateralLeg', alternatives:['Copenhagen plank','Affondo laterale'] },

    { id:'romanian-deadlift', name:'Stacchi Rumeni', aliases:['Stacco rumeno','Romanian deadlift','RDL','Stacchi rumeni bilanciere'], muscle:'Femorali', primary:['Femorali','Glutei'], secondary:['Erettori spinali','Adduttori'], equipment:['Bilanciere o manubri'], difficulty:'Intermedio', pattern:'hinge', alternatives:['Good Morning','Hyperextension'] },
    { id:'lying-leg-curl', name:'Leg Curl sdraiato', aliases:['Leg Curl','Lying leg curl','Leg curl prono'], muscle:'Femorali', primary:['Femorali'], secondary:['Gastrocnemio'], equipment:['Leg curl sdraiato'], difficulty:'Base', pattern:'kneeFlexion', alternatives:['Leg Curl seduto','Nordic Curl'] },
    { id:'seated-leg-curl', name:'Leg Curl seduto', aliases:['Seated leg curl','Leg curl seated'], muscle:'Femorali', primary:['Femorali'], secondary:['Gastrocnemio'], equipment:['Leg curl seduto'], difficulty:'Base', pattern:'kneeFlexion', alternatives:['Leg Curl sdraiato','Nordic Curl'] },
    { id:'nordic-curl', name:'Nordic Curl', aliases:['Nordic hamstring curl','Nordic ham curl'], muscle:'Femorali', primary:['Femorali'], secondary:['Glutei','Polpacci'], equipment:['Supporto caviglie'], difficulty:'Avanzato', pattern:'kneeFlexion', alternatives:['Leg Curl sdraiato','Leg Curl seduto'] },
    { id:'good-morning', name:'Good Morning', aliases:['Good morning bilanciere'], muscle:'Femorali', primary:['Femorali','Glutei'], secondary:['Erettori spinali'], equipment:['Bilanciere'], difficulty:'Avanzato', pattern:'hinge', alternatives:['Stacchi Rumeni','Hyperextension'] },
    { id:'standing-calf-raise', name:'Calf Raise in piedi', aliases:['Standing calf raise','Calf in piedi','Calf raise standing'], muscle:'Polpacci', primary:['Gastrocnemio'], secondary:['Soleo'], equipment:['Macchina o multipower'], difficulty:'Base', pattern:'calf', alternatives:['Calf Raise seduto','Calf press'] },
    { id:'seated-calf-raise', name:'Calf Raise seduto', aliases:['Seated calf raise','Calf seduto'], muscle:'Polpacci', primary:['Soleo'], secondary:['Gastrocnemio'], equipment:['Macchina calf seduto'], difficulty:'Base', pattern:'calf', alternatives:['Calf Raise in piedi','Calf press'] },
    { id:'calf-press', name:'Calf Press alla pressa', aliases:['Calf press','Calf alla leg press'], muscle:'Polpacci', primary:['Gastrocnemio','Soleo'], secondary:[], equipment:['Pressa'], difficulty:'Base', pattern:'calf', alternatives:['Calf Raise in piedi','Calf Raise seduto'] },
    { id:'single-leg-calf', name:'Calf Raise monopodalico', aliases:['Single leg calf raise','Calf gamba singola'], muscle:'Polpacci', primary:['Gastrocnemio','Soleo'], secondary:[], equipment:['Corpo libero o manubrio'], difficulty:'Base', pattern:'calf', alternatives:['Calf Raise in piedi','Calf Press alla pressa'] },

    { id:'plank', name:'Plank', aliases:['Plank frontale','Prone plank'], muscle:'Core', primary:['Retto addominale','Trasverso'], secondary:['Glutei','Obliqui'], equipment:['Corpo libero'], difficulty:'Base', pattern:'core', alternatives:['Dead Bug','Ab Wheel'] },
    { id:'side-plank', name:'Side Plank', aliases:['Plank laterale'], muscle:'Core', primary:['Obliqui'], secondary:['Gluteo medio','Trasverso'], equipment:['Corpo libero'], difficulty:'Base', pattern:'core', alternatives:['Pallof Press','Suitcase carry'] },
    { id:'cable-crunch', name:'Crunch ai cavi', aliases:['Cable crunch','Crunch al cavo alto'], muscle:'Addome', primary:['Retto addominale'], secondary:['Obliqui'], equipment:['Cavi','Corda'], difficulty:'Base', pattern:'core', alternatives:['Crunch','Ab Wheel'] },
    { id:'crunch', name:'Crunch', aliases:['Crunch a terra','Addominali crunch'], muscle:'Addome', primary:['Retto addominale'], secondary:['Obliqui'], equipment:['Corpo libero'], difficulty:'Base', pattern:'core', alternatives:['Crunch ai cavi','Reverse crunch'] },
    { id:'hanging-leg-raise', name:'Hanging Leg Raise', aliases:['Sollevamento gambe alla sbarra','Leg raise appeso'], muscle:'Addome', primary:['Retto addominale'], secondary:['Flessori dell’anca','Avambracci'], equipment:['Sbarra'], difficulty:'Avanzato', pattern:'core', alternatives:['Reverse crunch','Knee raise'] },
    { id:'ab-wheel', name:'Ab Wheel', aliases:['Ruota addominali','Ab rollout','Rollout'], muscle:'Core', primary:['Retto addominale','Trasverso'], secondary:['Gran dorsale','Tricipiti'], equipment:['Ruota addominali'], difficulty:'Avanzato', pattern:'core', alternatives:['Plank','Body saw'] },
    { id:'russian-twist', name:'Russian Twist', aliases:['Torsioni russe'], muscle:'Core', primary:['Obliqui'], secondary:['Retto addominale','Flessori dell’anca'], equipment:['Corpo libero o peso'], difficulty:'Base', pattern:'core', alternatives:['Pallof Press','Side Plank'] },
    { id:'dead-bug', name:'Dead Bug', aliases:['Deadbug'], muscle:'Core', primary:['Trasverso','Retto addominale'], secondary:['Flessori dell’anca'], equipment:['Corpo libero'], difficulty:'Base', pattern:'core', alternatives:['Plank','Bird Dog'] },

    { id:'decline-bench-press', name:'Panca declinata con bilanciere', aliases:['Decline bench press','Panca declinata'], muscle:'Petto', primary:['Grande pettorale'], secondary:['Tricipiti','Deltoide anteriore'], equipment:['Bilanciere','Panca declinata'], difficulty:'Intermedio', pattern:'horizontalPress', alternatives:['Dips per il petto','Chest press piana'] },
    { id:'flat-smith-press', name:'Panca piana Multipower', aliases:['Panca piana Smith Machine','Smith bench press'], muscle:'Petto', primary:['Grande pettorale'], secondary:['Tricipiti','Deltoide anteriore'], equipment:['Multipower','Panca'], difficulty:'Base', pattern:'horizontalPress', alternatives:['Panca piana con bilanciere','Chest press piana'] },
    { id:'cable-chest-press', name:'Chest Press ai cavi', aliases:['Cable chest press','Spinte ai cavi'], muscle:'Petto', primary:['Grande pettorale'], secondary:['Tricipiti','Deltoide anteriore'], equipment:['Cavi'], difficulty:'Intermedio', pattern:'horizontalPress', alternatives:['Chest press piana','Push-up'] },
    { id:'low-to-high-fly', name:'Croci ai cavi dal basso', aliases:['Low to high cable fly','Croci basse ai cavi'], muscle:'Petto alto', primary:['Fasci clavicolari del pettorale'], secondary:['Deltoide anteriore'], equipment:['Cavi'], difficulty:'Base', pattern:'fly', alternatives:['Chest press inclinata','Croci ai cavi'] },
    { id:'high-to-low-fly', name:'Croci ai cavi dall’alto', aliases:['High to low cable fly','Croci alte ai cavi'], muscle:'Petto', primary:['Grande pettorale'], secondary:['Deltoide anteriore'], equipment:['Cavi'], difficulty:'Base', pattern:'fly', alternatives:['Dips per il petto','Peck Deck'] },
    { id:'assisted-pull-up', name:'Trazioni assistite', aliases:['Assisted pull up','Trazioni macchina assistita'], muscle:'Dorso', primary:['Gran dorsale'], secondary:['Bicipiti','Grande rotondo'], equipment:['Macchina trazioni assistite'], difficulty:'Base', pattern:'verticalPull', alternatives:['Lat Machine','Trazioni alla sbarra'] },
    { id:'close-grip-pulldown', name:'Lat Machine presa stretta', aliases:['Close grip lat pulldown','Pulldown presa stretta'], muscle:'Dorso', primary:['Gran dorsale'], secondary:['Bicipiti','Grande rotondo'], equipment:['Lat machine'], difficulty:'Base', pattern:'verticalPull', alternatives:['Pulldown presa neutra','Lat Machine'] },
    { id:'landmine-row', name:'Landmine Row', aliases:['Rematore landmine','T bar row libera'], muscle:'Dorso', primary:['Gran dorsale','Romboidi'], secondary:['Trapezio','Bicipiti'], equipment:['Landmine','Bilanciere'], difficulty:'Intermedio', pattern:'horizontalPull', alternatives:['T-Bar Row petto supportato','Rematore con bilanciere'] },
    { id:'dumbbell-pullover', name:'Pullover con manubrio', aliases:['Dumbbell pullover','Pullover manubrio'], muscle:'Dorso', primary:['Gran dorsale'], secondary:['Grande pettorale','Tricipite capo lungo'], equipment:['Manubrio','Panca'], difficulty:'Intermedio', pattern:'verticalPull', alternatives:['Pullover ai cavi','Pulldown con fune'] },
    { id:'barbell-shrug', name:'Shrug con bilanciere', aliases:['Scrollate bilanciere','Barbell shrug'], muscle:'Trapezio', primary:['Trapezio superiore'], secondary:['Avambracci'], equipment:['Bilanciere'], difficulty:'Base', pattern:'horizontalPull', alternatives:['Shrug con manubri','Farmer walk'] },
    { id:'dumbbell-shrug', name:'Shrug con manubri', aliases:['Scrollate manubri','Dumbbell shrug'], muscle:'Trapezio', primary:['Trapezio superiore'], secondary:['Avambracci'], equipment:['Manubri'], difficulty:'Base', pattern:'horizontalPull', alternatives:['Shrug con bilanciere','Farmer walk'] },
    { id:'arnold-press', name:'Arnold Press', aliases:['Arnold shoulder press'], muscle:'Spalle', primary:['Deltoide anteriore','Deltoide laterale'], secondary:['Tricipiti'], equipment:['Manubri'], difficulty:'Intermedio', pattern:'verticalPress', alternatives:['Shoulder press con manubri','Military Press con bilanciere'] },
    { id:'front-raise', name:'Alzate frontali', aliases:['Front raise','Alzate frontali manubri'], muscle:'Spalle', primary:['Deltoide anteriore'], secondary:['Deltoide laterale'], equipment:['Manubri o cavo'], difficulty:'Base', pattern:'rearDelt', alternatives:['Military Press con bilanciere','Shoulder press macchina'] },
    { id:'reverse-cable-fly', name:'Croci inverse ai cavi', aliases:['Reverse cable fly','Rear delt cable fly'], muscle:'Deltoidi posteriori', primary:['Deltoide posteriore'], secondary:['Romboidi','Trapezio medio'], equipment:['Cavi'], difficulty:'Base', pattern:'rearDelt', alternatives:['Peck Back','Face Pull'] },
    { id:'cable-y-raise', name:'Y Raise ai cavi', aliases:['Cable Y raise','Y raise'], muscle:'Spalle', primary:['Deltoide laterale','Trapezio inferiore'], secondary:['Cuffia dei rotatori'], equipment:['Cavi'], difficulty:'Intermedio', pattern:'rearDelt', alternatives:['Alzate laterali ai cavi','Face Pull'] },
    { id:'ez-bar-curl', name:'Curl con bilanciere EZ', aliases:['EZ bar curl','Curl EZ'], muscle:'Bicipiti', primary:['Bicipite brachiale'], secondary:['Brachiale','Brachioradiale'], equipment:['Bilanciere EZ'], difficulty:'Base', pattern:'curl', alternatives:['Curl con bilanciere','Preacher Curl'] },
    { id:'spider-curl', name:'Spider Curl', aliases:['Curl spider'], muscle:'Bicipiti', primary:['Bicipite brachiale'], secondary:['Brachiale'], equipment:['Manubri o bilanciere EZ','Panca inclinata'], difficulty:'Intermedio', pattern:'curl', alternatives:['Preacher Curl','Curl su panca inclinata'] },
    { id:'reverse-curl', name:'Reverse Curl', aliases:['Curl inverso','Reverse barbell curl'], muscle:'Avambracci', primary:['Brachioradiale','Brachiale'], secondary:['Bicipite brachiale'], equipment:['Bilanciere o cavi'], difficulty:'Base', pattern:'curl', alternatives:['Hammer Curl','Wrist curl'] },
    { id:'cable-hammer-curl', name:'Hammer Curl ai cavi', aliases:['Rope hammer curl','Curl martello ai cavi'], muscle:'Bicipiti', primary:['Brachiale','Brachioradiale'], secondary:['Bicipite brachiale'], equipment:['Cavi','Corda'], difficulty:'Base', pattern:'curl', alternatives:['Hammer Curl','Curl ai cavi'] },
    { id:'single-arm-pushdown', name:'Pushdown monolaterale', aliases:['Single arm pushdown','Pushdown un braccio'], muscle:'Tricipiti', primary:['Tricipite brachiale'], secondary:[], equipment:['Cavi','Maniglia singola'], difficulty:'Base', pattern:'triceps', alternatives:['Pushdown con corda','Kickback tricipiti'] },
    { id:'overhead-dumbbell-extension', name:'Estensioni tricipiti sopra la testa con manubrio', aliases:['Overhead dumbbell triceps extension','French press manubrio'], muscle:'Tricipiti', primary:['Tricipite capo lungo'], secondary:['Tricipite laterale e mediale'], equipment:['Manubrio'], difficulty:'Base', pattern:'triceps', alternatives:['Estensioni dietro la nuca ai cavi','French Press'] },
    { id:'jm-press', name:'JM Press', aliases:['JM press bilanciere'], muscle:'Tricipiti', primary:['Tricipite brachiale'], secondary:['Petto','Deltoide anteriore'], equipment:['Bilanciere','Panca'], difficulty:'Avanzato', pattern:'horizontalPress', alternatives:['Panca presa stretta','Skull Crusher'] },
    { id:'goblet-squat', name:'Goblet Squat', aliases:['Squat goblet','Squat con manubrio'], muscle:'Quadricipiti', primary:['Quadricipiti','Glutei'], secondary:['Adduttori','Core'], equipment:['Manubrio o kettlebell'], difficulty:'Base', pattern:'squat', alternatives:['Front Squat','Hack Squat'] },
    { id:'belt-squat', name:'Belt Squat', aliases:['Squat con cintura'], muscle:'Quadricipiti', primary:['Quadricipiti','Glutei'], secondary:['Adduttori'], equipment:['Macchina belt squat'], difficulty:'Base', pattern:'squat', alternatives:['Hack Squat','Pressa 45 gradi'] },
    { id:'pendulum-squat', name:'Pendulum Squat', aliases:['Squat pendolare'], muscle:'Quadricipiti', primary:['Quadricipiti'], secondary:['Glutei','Adduttori'], equipment:['Macchina pendulum squat'], difficulty:'Base', pattern:'squat', alternatives:['Hack Squat','Pressa 45 gradi'] },
    { id:'reverse-lunge', name:'Affondo indietro', aliases:['Reverse lunge','Affondi posteriori'], muscle:'Gambe', primary:['Quadricipiti','Glutei'], secondary:['Adduttori','Core'], equipment:['Corpo libero o manubri'], difficulty:'Base', pattern:'unilateralLeg', alternatives:['Affondi camminati','Bulgarian Split Squat'] },
    { id:'lateral-lunge', name:'Affondo laterale', aliases:['Lateral lunge','Side lunge'], muscle:'Gambe', primary:['Adduttori','Glutei','Quadricipiti'], secondary:['Femorali'], equipment:['Corpo libero o manubrio'], difficulty:'Intermedio', pattern:'unilateralLeg', alternatives:['Adductor Machine','Cossack squat'] },
    { id:'cable-glute-kickback', name:'Glute Kickback ai cavi', aliases:['Cable glute kickback','Slanci glutei ai cavi'], muscle:'Glutei', primary:['Grande gluteo'], secondary:['Femorali'], equipment:['Cavi','Cavigliera'], difficulty:'Base', pattern:'unilateralLeg', alternatives:['Hip Thrust','Glute Bridge'] },
    { id:'cable-hip-abduction', name:'Abduzioni ai cavi', aliases:['Cable hip abduction','Abduzione gamba al cavo'], muscle:'Glutei', primary:['Gluteo medio','Gluteo minimo'], secondary:['Tensore fascia lata'], equipment:['Cavi','Cavigliera'], difficulty:'Base', pattern:'unilateralLeg', alternatives:['Abductor Machine','Camminata laterale con elastico'] },
    { id:'sumo-deadlift', name:'Stacco Sumo', aliases:['Sumo deadlift','Stacco sumo bilanciere'], muscle:'Catena posteriore', primary:['Glutei','Adduttori','Femorali'], secondary:['Erettori spinali','Quadricipiti'], equipment:['Bilanciere'], difficulty:'Avanzato', pattern:'hinge', alternatives:['Stacco da terra','Trap bar deadlift'] },
    { id:'stiff-leg-deadlift', name:'Stacco a gambe tese', aliases:['Stiff leg deadlift','Stiff-legged deadlift'], muscle:'Femorali', primary:['Femorali'], secondary:['Glutei','Erettori spinali'], equipment:['Bilanciere o manubri'], difficulty:'Intermedio', pattern:'hinge', alternatives:['Stacchi Rumeni','Good Morning'] },
    { id:'single-leg-rdl', name:'Stacco Rumeno monopodalico', aliases:['Single leg RDL','Stacco rumeno una gamba'], muscle:'Femorali', primary:['Femorali','Glutei'], secondary:['Core','Gluteo medio'], equipment:['Manubri o bilanciere'], difficulty:'Intermedio', pattern:'hinge', alternatives:['Stacchi Rumeni','Glute Kickback ai cavi'] },
    { id:'glute-ham-raise', name:'Glute Ham Raise', aliases:['GHR','Glute ham developer'], muscle:'Femorali', primary:['Femorali','Glutei'], secondary:['Polpacci','Erettori spinali'], equipment:['GHD'], difficulty:'Avanzato', pattern:'kneeFlexion', alternatives:['Nordic Curl','Leg Curl sdraiato'] },
    { id:'tibialis-raise', name:'Tibialis Raise', aliases:['Sollevamento tibiale','Tibialis anterior raise'], muscle:'Tibiali', primary:['Tibiale anteriore'], secondary:[], equipment:['Corpo libero o macchina'], difficulty:'Base', pattern:'calf', alternatives:['Camminata sui talloni','Dorsiflessione con elastico'] },
    { id:'pallof-press', name:'Pallof Press', aliases:['Pallof press ai cavi'], muscle:'Core', primary:['Obliqui','Trasverso'], secondary:['Glutei','Spalle'], equipment:['Cavi o elastico'], difficulty:'Base', pattern:'core', alternatives:['Side Plank','Dead Bug'] },
    { id:'reverse-crunch', name:'Reverse Crunch', aliases:['Crunch inverso'], muscle:'Addome', primary:['Retto addominale'], secondary:['Obliqui'], equipment:['Corpo libero'], difficulty:'Base', pattern:'core', alternatives:['Hanging Leg Raise','Crunch'] },
    { id:'bicycle-crunch', name:'Bicycle Crunch', aliases:['Crunch bicicletta'], muscle:'Addome', primary:['Obliqui','Retto addominale'], secondary:['Flessori dell’anca'], equipment:['Corpo libero'], difficulty:'Base', pattern:'core', alternatives:['Russian Twist','Dead Bug'] },
    { id:'bird-dog', name:'Bird Dog', aliases:['Bird-dog'], muscle:'Core', primary:['Erettori spinali','Trasverso'], secondary:['Glutei','Spalle'], equipment:['Corpo libero'], difficulty:'Base', pattern:'core', alternatives:['Dead Bug','Plank'] },
  ];

  const catalog = raw.map(item => {
    const template = templates[item.pattern] || templates.core;
    return Object.freeze({
      ...template,
      ...item,
      setup: Object.freeze([...(template.setup || []), ...(item.setup || [])]),
      execution: Object.freeze([...(template.execution || []), ...(item.execution || [])]),
      errors: Object.freeze([...(template.errors || []), ...(item.errors || [])]),
      tips: Object.freeze([...(template.tips || []), ...(item.tips || [])]),
      aliases: Object.freeze(item.aliases || []),
      primary: Object.freeze(item.primary || []),
      secondary: Object.freeze(item.secondary || []),
      equipment: Object.freeze(item.equipment || []),
      alternatives: Object.freeze(item.alternatives || []),
      youtubeQuery: item.youtubeQuery || `${item.name} esecuzione corretta tecnica`,
    });
  });

  window.VANTA_EXERCISE_CATALOG = Object.freeze(catalog);
})();
